### ISSUE TITLE
feature request: Feats of Strength

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/mod-pvp-titles#9]
https://wotlkdb.com/?achievement=433

These FoS were added when Blizzard removed the Rank 1-14 system. Since there is no way to obtain them in Wrath, we could give them alongside the titles and add a config flag for it.

**Comment by Nyeriah** [comment]
https://github.com/azerothcore/mod-pvp-titles/commit/32eff4812567f7fb5741dce2a3818bd56b0a89c6
